//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptiMice_Assign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int b_id { get; set; }
        public string b_author { get; set; }
        public string b_img { get; set; }
        public string b_title { get; set; }
        public string b_content { get; set; }
        public Nullable<int> cat_id_fk { get; set; }
        public Nullable<int> b_adm_id_fk { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual category category { get; set; }
    }
}
